#!env bash

FILENAME="do/publish"

if [ "$0" != "$FILENAME" ]; then
	echo "error: must be called as ${FILENAME} from project directory"
	echo "exiting"
	exit
fi

echo -n "started "
date 

echo "publishing with rsyn over ssh..."

echo -n "finished "
date

